DJGPP = A:\PROGS\DJGPP
CC = $(DJGPP)\BIN\GCC.EXE
OBJS = MAIN.O DATUM.O P98.O
TARGET = KOARMADA.EXE

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(OBJS) -o $(TARGET)

MAIN.O: MAIN.C
	$(CC) -x c -c MAIN.C -o MAIN.O
DATUM.O: DATUM.C
	$(CC) -x c -c DATUM.C -o DATUM.O
P98.O: P98.C
	$(CC) -x c -c P98.C -o P98.O

clean:
	del main.o
	del datum.o
	del p98.o
	del koarmada.exe
